# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
        
      - name: Run platformIO
        run: platformio run
      
      - name: Set Version Variable
        run:
          FIRMWARE_VERSION=$(cat .pio/build/esp32dev/last_version.txt)
          echo "FIRMWARE_VERSION=$FIRMWARE_VERSION" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:         
          path: |
            .pio/build/esp32dev/*.bin
            .pio/build/esp32dev/last_version.txt
                
      - name: Deploy Firmware to Azure Blob Storage
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          container_name: firmwares
          source_folder: .pio/build/esp32dev/firmware_{{ env.FIRMWARE_VERSION }}.bin            

      - name: Deploy Version to Azure Blob Storage
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          container_name: firmwares
          source_folder: .pio/build/esp32dev/last_version.txt
